# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=64)),
                ('secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('createTime', models.DateTimeField()),
                ('discussNum', models.IntegerField(default=0)),
                ('supportNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1024)),
                ('discussoneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.DiscussOne')),
            ],
        ),
        migrations.CreateModel(
            name='SupportDisone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('discussoneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.DiscussOne')),
            ],
        ),
        migrations.CreateModel(
            name='SupportThought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=8192)),
                ('discussNum', models.IntegerField(default=0)),
                ('supportNum', models.IntegerField(default=0)),
                ('duration', models.FloatField()),
                ('weight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxId', models.CharField(max_length=128)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('photoUrl', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='thought',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.User'),
        ),
        migrations.AddField(
            model_name='supportthought',
            name='thoughtId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.Thought'),
        ),
        migrations.AddField(
            model_name='supportthought',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.User'),
        ),
        migrations.AddField(
            model_name='supportdisone',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.User'),
        ),
        migrations.AddField(
            model_name='discusstwo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.User'),
        ),
        migrations.AddField(
            model_name='discussone',
            name='thoughtId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.Thought'),
        ),
        migrations.AddField(
            model_name='discussone',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thought.User'),
        ),
    ]
