# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussone',
            name='auther',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='discusstwo',
            name='auther',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='thought',
            name='auther',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
