# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0003_auto_20180518_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussone',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
