# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0005_auto_20180705_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time', models.FloatField(default=1)),
                ('sup', models.FloatField(default=1)),
                ('dis', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='thought',
            name='selfW',
            field=models.FloatField(default=0),
        ),
    ]
