# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0006_auto_20180803_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
