# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-10 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0007_auto_20180807_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
